name = "Justtext"
license = "MIT"
licenselink = "https://opensource.org/licenses/MIT"
description = ""
homepage = "https://husio.github.io/"
tags = []
features = []
min_version = "0.41"

[author]
  name = "Piotr Husiatyński"
  homepage = "https://husio.github.io/"
